"""Adds necessary repostories/archives."""

########################################################################
# DO NOT EDIT THIS FILE unless you are inside the
# https://github.com/3rdparty/bazel-rules-rapidjson repository. If you
# encounter it anywhere else it is because it has been copied there in
# order to simplify adding transitive dependencies. If you want a
# different version of bazel-rules-rapidjson follow the Bazel build
# instructions at https://github.com/3rdparty/bazel-rules-rapidjson.
########################################################################

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

def repos(external = True, repo_mapping = {}):
    if external:
        maybe(
            git_repository,
            name = "com_github_3rdparty_bazel_rules_rapidjson",
            remote = "https://github.com/3rdparty/bazel-rules-rapidjson",
            commit = "2f16f77354d88fb0fe48758d7791b01b2e85e76f",
            shallow_since = "1633890789 +0300",
            repo_mapping = repo_mapping,
        )
